log:
  level: DEBUG

# ui:
#   enabled: true

# cache:
#   memory:
#     enabled: true

# server:
#   host: 0.0.0.0
#   http_port: 8000
#   grpc_port: 9000

db:
  url: sqlite3://flipt.db
  migrations:
    auto: true
    path: ./config/migrations
